"""
Check alerts generated by correlation engine.
"""
import psycopg2
from dotenv import load_dotenv
import os

load_dotenv()

db_config = {
    'dbname': os.getenv('DB_NAME', 'bgp_monitor'),
    'user': os.getenv('DB_USER', 'postgres'),
    'password': os.getenv('DB_PASSWORD', ''),
    'host': os.getenv('DB_HOST', 'localhost'),
    'port': os.getenv('DB_PORT', '5432')
}

try:
    conn = psycopg2.connect(**db_config)
    cursor = conn.cursor()
    
    # Check if alerts table exists
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'alerts'
        );
    """)
    table_exists = cursor.fetchone()[0]
    
    if not table_exists:
        print("WARNING: Alerts table does not exist!")
    else:
        # Check total alerts
        cursor.execute("SELECT COUNT(*) FROM alerts;")
        total = cursor.fetchone()[0]
        print(f"[OK] Total alerts: {total}")
        
        if total > 0:
            # Check by severity
            cursor.execute("""
                SELECT severity, COUNT(*) 
                FROM alerts 
                GROUP BY severity 
                ORDER BY 
                    CASE severity 
                        WHEN 'critical' THEN 1 
                        WHEN 'high' THEN 2 
                        WHEN 'medium' THEN 3 
                        WHEN 'low' THEN 4 
                    END;
            """)
            print("\nAlerts by severity:")
            for row in cursor.fetchall():
                print(f"  {row[0].upper()}: {row[1]}")
            
            # Show latest alerts
            cursor.execute("""
                SELECT alert_type, severity, peer_addr, description
                FROM alerts
                ORDER BY created_at DESC
                LIMIT 5;
            """)
            print("\nLatest 5 alerts:")
            for row in cursor.fetchall():
                print(f"  [{row[1].upper()}] {row[0]}: {row[2]} - {row[3][:60]}...")
    
    cursor.close()
    conn.close()
    
except Exception as e:
    print(f"Error: {e}")
